<script setup lang="ts">
import {computed,ref,watch,nextTick} from 'vue';
import type {Controller} from './controller';
import type {DatabaseAppearance} from './appearance';
import { discoverDatabaseApi, CHAT_BOUND_PROJECTION_PROTOCOL } from './database';
import { compareAmounts, subtractAmounts, multiplyAmountByCount, BASELINE_QUOTE_ID } from './core';
import {SPEC_LABELS} from './protocol';
import {hasChat} from './host';
const props=defineProps<{controller:Controller;assetUrl:string;appearance:DatabaseAppearance}>();
const c=props.controller,s=c.state;
const a=props.appearance;
const databaseSupport=computed(()=>{
  void s.tab;void s.syncStatus;const api=discoverDatabaseApi();if(!api)return 'missing';
  try {const bridge=api.getChatBoundProjectionContext?.();return typeof api.applyChatBoundProjection==='function'&&bridge?.protocol===CHAT_BOUND_PROJECTION_PROTOCOL&&bridge.patchVersion==='1.2.5-shiro.1'?'safe':'export';}
  catch{return 'export';}
});
const chibiUrl=props.assetUrl.replace(/shiro\.png$/, 'shiro-chibi.png');
const tabs=[['home','开始使用','⌂'],['shop','兑换商店','♙'],['quests','剧情委托','♧'],['memory','记忆四表','▤'],['inventory','已购所得','◇'],['ledger','事件与点数','✦'],['database','导入数据库','▦'],['settings','设置与备份','⚙']];
const chatAvailable=computed(()=>{void s.world;void s.open;void s.tab;return hasChat();});
const activeQuests=computed(()=>s.ledger?.quests?.filter(q=>q.status==='active')??[]);
const nextStep=computed(()=>{
  if(!chatAvailable.value)return {title:'先打开要玩的角色聊天',detail:'世界识别和计点都需要这段聊天作为依据。回到酒馆打开聊天，再点白的入口。',tab:'',action:'回到酒馆聊天'};
  if(!s.worldEvidence||s.world==='世界信息不足')return {title:'先确认当前世界',detail:'在兑换商店填写想获得的能力或物品，再识别世界。信息不足时可在设置中补充世界资料。',tab:'shop',action:'去识别世界与匹配商品'};
  if(!s.ledger?.events.length)return {title:'先让剧情里发生实际改变',detail:'回聊天推进故事，再到“事件与点数”核对最新 AI 正文。只有已经成立的改变才计点，填写愿望不会加点。',tab:'ledger',action:'去核对事件与点数'};
  if(!s.ledger?.inventory.length)return {title:'选择第一份要兑换的所得',detail:'查看完整效果、份数和总价，确认后才扣点；购买结果保存在“已购所得”。',tab:'shop',action:'去兑换商店'};
  return {title:activeQuests.value.length?'继续推进已接取的委托':'选一个接下来要推进的目标',detail:'委托只是剧情建议。接取后回聊天行动，实际完成的结果统一在“事件与点数”核对。',tab:'quests',action:'查看剧情委托'};
});
function goNext(){if(nextStep.value.tab)s.tab=nextStep.value.tab;else c.close();}
const rippleDescription=(id:string)=>s.ledger?.ripples.find(r=>r.id===id)?.tracking??'原始关联未找到，请在事件与点数中核对';
const outcomeDescription=(id:string)=>s.ledger?.events.find(e=>e.id===id)?.outcome??'请在事件与点数中查看结算记录';
const categories=computed(()=>['全部',...new Set((s.ledger?.quotes??[]).map(q=>q.category))]);
const products=computed(()=>s.ledger?.quotes.filter(q=>
  (q.id===BASELINE_QUOTE_ID||s.activeIds.includes(q.id)||(s.activeIds.length===0&&q.world===s.world))&&
  (s.category==='全部'||q.category===s.category)&&
  (!s.search||[q.name,q.spec.content,q.category,...q.aliases].join(' ').toLowerCase().includes(s.search.toLowerCase()))&&
  (!s.affordable||compareAmounts(s.ledger!.balance,q.price)>=0))??[]);
const quests=computed(()=>[...(s.ledger?.quests??[])].reverse());
const impressionArchive=computed(()=>[...(s.ledger?.impressions??[])].reverse().filter(i=>!s.memoryQuery||[i.subject,i.summary,i.world].join(' ').includes(s.memoryQuery)));
const totalPrice=computed(()=>{try{return s.selectedQuote?multiplyAmountByCount(s.selectedQuote.price,s.quantity):'';}catch{return '';}});
const totalShortfall=computed(()=>totalPrice.value?shortfall(totalPrice.value):'');
const input=ref<HTMLInputElement>();const inventoryModal=ref<{id:string;name:string;action:'use'|'transfer';max:number}|null>(null),inventoryQuantity=ref(1),recipient=ref('');
const shortfall=(price:string)=>s.ledger&&compareAmounts(s.ledger.balance,price)<0?subtractAmounts(price,s.ledger.balance):'';
const changeAccount=(e:Event)=>c.selectAccount((e.target as HTMLSelectElement).value);
function choose(q:any){s.selectedQuote=q;s.quantity=1;}
function openInventory(i:any,action:'use'|'transfer'){inventoryModal.value={id:i.id,name:i.name,action,max:i.remaining};inventoryQuantity.value=1;recipient.value='';}
async function commitInventory(){if(!inventoryModal.value)return;await c.inventoryAction(inventoryModal.value.id,inventoryModal.value.action,inventoryQuantity.value,recipient.value);if(!s.error)inventoryModal.value=null;}
async function importFile(e:Event){const target=e.target as HTMLInputElement;if(target.files?.[0])await c.importLedger(target.files[0]);target.value='';}
const assetBase=props.assetUrl.substring(0,props.assetUrl.lastIndexOf('/assets/'));
const content=ref<HTMLElement>(),navigation=ref<HTMLElement>();
watch(()=>[s.tab,s.open],async()=>{
  await nextTick();
  if(!s.open)return;
  content.value?.scrollTo({top:0});
  const nav=navigation.value,active=nav?.querySelector<HTMLElement>('[aria-current="page"]');
  if(nav&&active&&nav.scrollWidth>nav.clientWidth){
    const nr=nav.getBoundingClientRect(),ar=active.getBoundingClientRect();
    nav.scrollLeft+=ar.left-nr.left-(nav.clientWidth-ar.width)/2;
  }
});
</script>

<template>
  <button v-if="!s.open" class="launcher" type="button" title="点击打开蝶翼商店；拖动可移动入口" aria-label="打开白·蝶翼商店，可拖动" @click="c.open()"><img class="launcher-chibi" :src="chibiUrl" alt="Q版白"/><b>蝶翼商店</b><small v-if="s.ledger">{{s.ledger.balance}} 点</small><i v-if="s.error" aria-label="需要处理">!</i></button>
  <div v-if="s.open" class="veil" @click.self="c.close()" @keydown.esc="s.selectedQuote ? s.selectedQuote=null : inventoryModal ? inventoryModal=null : c.close()">
    <section class="window" role="dialog" aria-modal="true" aria-labelledby="shop-heading" tabindex="-1">
      <header class="topbar"><a class="brand" href="#" @click.prevent="s.tab='home'"><span class="brandmark chibi-mark"><img :src="chibiUrl" alt="Q版白小助手"/></span><span><b id="shop-heading">白 · 蝶翼商店</b><small>SHIRO / BUTTERFLY ARCHIVE</small></span></a><div class="topright"><span class="status"><i :class="{busy:s.busy,error:!!s.error}"></i>{{s.busy?s.status:!s.ready?'正在读取账本':s.error?'需要处理':s.settings.accountId?'账本已载入':'尚未建立账户'}}</span><button class="icon-button" type="button" aria-label="关闭商店" @click="c.close()">×</button></div></header>
      <div class="body">
        <aside class="rail"><div class="rail-caption">记下改变，选择下一步。</div><nav ref="navigation" aria-label="商店导航"><button v-for="[id,label,icon] in tabs" :key="id" type="button" :class="{active:s.tab===id}" :aria-current="s.tab===id?'page':undefined" @click="s.tab=id"><span aria-hidden="true">{{icon}}</span>{{label}}<b v-if="id==='inventory'&&s.ledger?.inventory.length">{{s.ledger.inventory.length}}</b></button></nav><div class="rail-bottom"><img class="rail-chibi" :src="chibiUrl" alt="Q版白坐在白棋旁"/><p class="shiro-aside">{{s.busy?s.status:'不知道从哪开始？打开“开始使用”。'}}</p><b>一份本源，万千世界</b><p>恒量不变，所得长存。</p><button class="text-button" @click="s.tab='settings'">账户与备份 ↗</button></div></aside>
        <main ref="content" class="content">
          <div class="alerts" aria-live="polite"><div v-if="s.error" class="alert error"><b>未完成本次操作</b><p>{{s.error}}</p><button @click="s.error=''" aria-label="关闭错误提示">×</button></div><div v-else-if="s.notice" class="alert success">{{s.notice}}<button @click="s.notice=''" aria-label="关闭通知">×</button></div></div>
          <section v-if="s.tab==='database'&&!s.settings.accountId" class="record"><h2>白 · 空白棋局数据库主题</h2><label class="check"><input type="checkbox" :disabled="!a.state.available" :checked="a.state.enabled" @change="a.setEnabled(($event.target as HTMLInputElement).checked)"/>启用完整白主题与 Q 版白</label><p>{{a.state.error||a.state.status}}</p><p>白主题使用独立的酒馆助手脚本：在全局脚本库导入并启用，无需建立本源账户。此处只控制已经运行的主题。</p></section>
          <p v-if="!s.settings.accountId && ['memory','quests'].includes(s.tab)" class="note">先建立或接续一份本源，就能使用四表记忆与白的委托；原有点数与档案会随所选本源读取。</p>
          <section v-if="!s.settings.accountId" class="welcome"><span class="eyebrow">THE FIRST MOVE</span><h1>先建一份账本，<br>再开始这段故事。</h1><p>本源就是你的跨世界账本，用来保留点数、已购所得和重要记忆。首次从 0 点开始；已经用过就接续已有账户或恢复备份。</p><label>账本名称<input v-model="s.accountLabel" maxlength="256" placeholder="我的本源" /></label><button class="primary" :disabled="!s.ready" @click="c.createAccount()">建立账本 · 从 0 点开始</button><template v-if="s.accounts.length"><label>接续已有本源<select :value="s.settings.accountId" @change="changeAccount"><option value="" disabled>选择本源</option><option v-for="a in s.accounts" :value="a.accountId">{{a.label}} · {{a.balance}} 点</option></select></label></template><button class="text-button" @click="input?.click()">或恢复完整账本备份</button><p class="setup-cost">默认会在进入聊天时识别世界、故事回复后核对因果，使用你已配置的 API。下方可先关闭自动功能，创建后也能在设置中更改。</p><div class="setup-options"><label class="check"><input type="checkbox" v-model="s.settings.autoWorld" @change="c.saveSettings()"/>自动识别世界</label><label class="check"><input type="checkbox" v-model="s.settings.autoSettle" @change="c.saveSettings()"/>回复后自动核对事件</label></div><img :src="assetUrl" alt="白手持棋子，蝶翼环绕"/></section>

          <template v-else-if="s.ledger">
            <div v-if="!chatAvailable && ['shop','quests','ledger','memory'].includes(s.tab)" class="note" role="status">当前未打开角色聊天。请先回酒馆打开聊天，再识别世界、核对事件、生成委托或导出本轮四表。已保存的账本仍可查看。<button class="text-button" @click="c.close()">回到聊天</button></div>
            <template v-if="s.tab==='home'">
              <section class="start-heading"><span class="eyebrow">白 · 蝶翼商店</span><h1>这次想推动什么故事？</h1><p>从聊天里的实际改变获得因果点，用点数兑换所得，再把重要记忆留给下一轮。</p></section>
              <section class="next-step" aria-label="当前建议"><span class="tag">建议下一步</span><h2>{{nextStep.title}}</h2><p>{{nextStep.detail}}</p><button class="primary" @click="goNext()">{{nextStep.action}} →</button></section>
              <dl class="session-facts"><dt>当前世界</dt><dd>{{s.world}}</dd><dt>使用账本</dt><dd>{{s.ledger.label}}</dd><dt>可用点数</dt><dd>{{s.ledger.balance}} 点</dd><dt>生成连接</dt><dd>{{s.settings.provider==='host'?'酒馆当前 API':'数据库 API 预设'}} · <button class="text-button" @click="s.tab='settings'">检查设置</button></dd></dl>
              <div class="start-steps" aria-label="使用顺序">
                <button @click="s.tab='shop'"><span class="step-number">1</span><div><b>识别世界，挑选商品</b><p>填写想得到的能力或物品，按当前聊天匹配。识别会调用所选 API。</p><small>前往兑换商店 →</small></div></button>
                <button @click="s.tab='ledger'"><span class="step-number">2</span><div><b>推进故事，核对点数</b><p>先在聊天里行动，再核对最新 AI 正文中已成立的改变。不会预支未来收益。</p><small>前往事件与点数 →</small></div></button>
                <button @click="s.tab='shop'"><span class="step-number">3</span><div><b>确认规格，扣点兑换</b><p>看清效果、份数和总价后确认。购买后的内容在“已购所得”查看。</p><small>去选择一份所得 →</small></div></button>
                <button @click="s.tab='quests'"><span class="step-number">4</span><div><b>选择委托，继续剧情</b><p>白根据人物和连锁反应推荐方向。接取后回聊天推进，实际结果再统一计点。</p><small>前往剧情委托 →</small></div></button>
              </div>
              <section class="record"><h2>四表分别记住什么？</h2><p>重要印象记人物与承诺；点数账目记收入和余额；消费与所得记买过、用过什么；连锁反应记尚待推进的后果。完整历史留在账本，每轮按预算提供摘要。</p><div class="button-row"><button class="secondary" @click="s.tab='memory'">查看四表与记忆预算</button><button class="text-button" @click="s.tab='database'">如何导入原数据库 →</button></div></section>
            </template>
            <template v-else-if="s.tab==='shop'">
              <section class="hero"><div class="hero-copy"><span class="eyebrow">EVERY CHOICE LEAVES A TRACE</span><h1>选择当前世界<br>用得上的能力与物品。</h1><p>先识别世界，再看完整规格。只有确认兑换才会扣除因果点。</p><div class="world-pill"><span>◈</span><div><small>当前世界</small><b>{{s.world}}</b></div></div><div class="systems"><span v-for="system in s.systems">{{system}}</span></div></div><img class="shiro" :src="assetUrl" alt="游戏人生的白，手持白棋与发光蝴蝶"/><div class="hero-chess" aria-hidden="true">♜</div></section>
              <section class="wallet" aria-label="因果点余额"><div class="balance"><span>可用因果点</span><strong>{{s.ledger.balance}}<small>POINTS</small></strong></div><div><span>累计入账</span><b>+ {{s.ledger.income}}</b></div><div><span>累计消费</span><b>− {{s.ledger.spend}}</b></div><button class="text-button" @click="s.tab='ledger'">查看因果账本 ↗</button></section>
              <div class="section-title"><div><span class="eyebrow">WORLD COLLECTION</span><h2>随界商店 <small>{{products.length}} 件</small></h2></div><button class="secondary" :disabled="s.busy||!chatAvailable" @click="c.generateWorld()">{{s.busy?'匹配中…':'识别当前世界 / 更新商品'}}</button></div>
              <label class="field-caption" for="wish-input">想获得什么？用于匹配商品，不会直接增加点数。</label><form class="wish" @submit.prevent="c.generateWorld()"><label class="sr-only" for="wish-input">想获得的能力或物品</label><span>✧</span><input id="wish-input" v-model="s.goal" placeholder="例如：护送商队穿越雪原，需要耐寒与急救" maxlength="2000"/><button type="submit" :disabled="s.busy||!chatAvailable">按目标匹配商品 →</button></form>
              <p class="action-context">世界和商品来自当前角色、最近聊天与世界资料，匹配会调用所选 API。<button class="text-button" @click="s.tab='settings'">世界不对或信息不足？补充资料 →</button></p><div v-if="s.ledger.balance==='0'" class="note">目前是 0 点。先在聊天里促成实际改变，再核对已发生事件。<button class="text-button" @click="s.tab='ledger'">去核对事件与点数 →</button></div><div class="filters"><label><span class="sr-only">搜索商品</span><input v-model="s.search" placeholder="搜索名称、效果…"/></label><label><span class="sr-only">商品体系</span><select v-model="s.category"><option v-for="category in categories">{{category}}</option></select></label><label class="check"><input type="checkbox" v-model="s.affordable"/>只看可负担</label></div>
              <div class="products"><article v-for="q in products" :key="q.id" class="product" :class="{baseline:q.id===BASELINE_QUOTE_ID}"><div class="product-meta"><span>{{q.category}}</span><span>{{q.id===BASELINE_QUOTE_ID?'恒定基准':q.kind==='permanent'?'永久所得':q.kind==='consumable'?'消耗资源':'装备 / 资产'}}</span></div><div class="product-icon" aria-hidden="true">{{q.id===BASELINE_QUOTE_ID?'♙':q.kind==='permanent'?'✦':q.kind==='consumable'?'❖':'♜'}}</div><h3>{{q.name}}</h3><p>{{q.spec.content}}</p><div class="product-spec"><span>{{q.spec.duration}}</span><span>{{q.spec.quantity}}</span></div><footer><div><strong>{{q.price}}<small> 点</small></strong><span v-if="shortfall(q.price)" class="shortfall">还差 {{shortfall(q.price)}} 点</span><span v-else class="affordable">完整可兑换</span></div><button class="secondary" @click="choose(q)">查看规格 ↗</button></footer></article></div>
              <div v-if="!products.length" class="empty"><span>♙</span><h3>还没有符合筛选的商品</h3><p>可以清除筛选，或让白为当前世界匹配奖励。</p></div>
              <details class="explanation"><summary>查看世界识别依据与定价规则</summary><p>{{s.worldEvidence||'打开聊天后，使用酒馆当前连接或数据库 API 识别。'}}</p><p>同一完整效果规格沿用原价；名称与包装不参与定价。新规格会永久保存。模型对因果和语义的判断可在账本中逐条核对。</p></details>
            </template>

            <template v-else-if="s.tab==='inventory'"><div class="section-title"><div><span class="eyebrow">YOURS, ACROSS WORLDS</span><h1>我的所得</h1><p>完整到账，跨界接续。一次性资源按实际使用记录。</p></div></div><div v-if="!s.ledger.inventory.length" class="empty"><span>◇</span><h3>棋盘上的第一份所得，等待你的选择</h3><button class="primary" @click="s.tab='shop'">去商店看看 →</button></div><div class="inventory-list"><article v-for="i in [...s.ledger.inventory].reverse()" :key="i.id" class="record"><div class="record-top"><h3>{{i.name}}</h3><span class="tag">{{i.kind==='permanent'?'永久保留':`剩余 ${i.remaining} / ${i.acquired}`}}</span></div><p>{{i.spec.content}}</p><dl><template v-for="(label,field) in SPEC_LABELS"><dt>{{label}}</dt><dd>{{i.spec[field]}}</dd></template></dl><div class="record-bottom"><small>取得于 {{i.world}} · {{new Date(i.at).toLocaleString()}}</small><div><button v-if="i.kind==='consumable'&&i.remaining>0" class="secondary" @click="openInventory(i,'use')">登记实际消耗</button><button v-if="i.kind!=='permanent'&&i.remaining>0" class="text-button" @click="openInventory(i,'transfer')">记录移交</button></div></div></article></div></template>

            <template v-else-if="s.tab==='ledger'"><div class="section-title"><div><span class="eyebrow">CAUSAL ARCHIVE</span><h1>事件与点数</h1><p>先看故事发生了什么，再核对本轮新增收益。</p></div><button class="primary" :disabled="s.busy||!chatAvailable" @click="c.settle()">{{s.busy?'核对中…':'核对最新故事事件并计点'}}</button></div><section class="wallet"><div class="balance"><span>当前余额</span><strong>{{s.ledger.balance}}</strong></div><div><span>累计入账</span><b>{{s.ledger.income}}</b></div><div><span>累计消费</span><b>{{s.ledger.spend}}</b></div></section><div class="note">核对会调用所选 API，只接受最新一条已完成 AI 故事正文中的事实。先在聊天里推进故事，再点上方按钮；愿望、未完成委托和未来后果不会提前加点，相同结果不重复入账。</div><h2>最近结算回执</h2><pre v-if="s.receipt" class="receipt">{{s.receipt}}</pre><div v-else class="empty compact">暂无结算记录。回聊天完成一次实际行动，再回来核对。打开页面或接取委托都不会赠送点数。</div><button v-if="s.receipt" class="text-button" @click="c.downloadReceipt()">下载 WJWK-settle 回执 ↓</button><h2>交易记录 <small>{{s.ledger.transactions.length}}</small></h2><div class="table-scroll"><table><thead><tr><th>时间</th><th>类型 / 来源世界</th><th>实量</th><th>余额</th><th>回执</th></tr></thead><tbody><tr v-for="t in [...s.ledger.transactions].reverse()" :key="t.id"><td>{{new Date(t.at).toLocaleString()}}</td><td>{{({credit:'因果计功',purchase:'兑换',use:'消耗',transfer:'移交'})[t.kind]}}<small>{{t.world}}</small></td><td :class="{positive:t.kind==='credit'}">{{t.kind==='credit'?'+':t.kind==='purchase'?'−':''}}{{t.amount}}</td><td>{{t.balanceAfter}}</td><td><button class="text-button" @click="s.receipt=t.receipt">查看</button></td></tr></tbody></table></div><details class="explanation"><summary>成立证据与固定计功参照（{{s.ledger.events.length}}）</summary><article v-for="e in s.ledger.events" class="evidence"><b>{{e.outcome}} · +{{e.amount}}</b><p>归因：{{e.source}}</p><blockquote>{{e.evidence}}</blockquote><small>{{e.kind}} · {{e.id}}</small></article></details><details class="explanation"><summary>正在追踪的余波（{{s.ledger.ripples.length}}）</summary><article v-for="r in s.ledger.ripples" class="evidence"><b>{{r.source}} · {{r.world}}</b><p>已结算：{{r.settled}}</p><p>追踪：{{r.tracking}}</p><span class="tag">{{r.status==='active'?'持续追踪':'已结束'}}</span></article></details><details class="explanation"><summary>永久报价档案（{{s.ledger.quotes.length}}）</summary><article v-for="q in s.ledger.quotes" class="evidence"><b>{{q.name}} · {{q.price}} 点</b><p>{{q.spec.content}}</p><p v-if="q.differences?.length">新版实际差异：{{q.differences.map(k=>SPEC_LABELS[k]).join('、')}}</p><button class="text-button" @click="choose(q)">查看完整规格 / 兑换</button></article></details></template>

            <template v-else-if="s.tab==='quests'">
              <section class="quest-hero"><div><span class="eyebrow">SHIRO'S NEXT MOVE</span><h1>剧情委托</h1><p>从已经发生的改变，找到下一步可以走的路。</p><p class="subtle">顺序：生成建议 → 接取 → 回聊天推进 → 目标实际成立后核对。接取只记录目标，不会代发聊天、自动完成或直接发点。</p></div><img :src="chibiUrl" alt="白正在思考下一步委托"/></section>
              <label class="field-caption" for="quest-goal">想推进谁、什么事件，或哪条连锁反应？</label><form class="wish" @submit.prevent="c.dispatchTasks()"><label class="sr-only" for="quest-goal">委托方向</label><input id="quest-goal" v-model="s.goal" placeholder="例如：调查港口失踪事件，先找失踪者的同伴" maxlength="2000"/><button :disabled="s.busy||!chatAvailable" type="submit">根据当前剧情推荐委托</button></form>
              <div v-if="!quests.length" class="empty"><span>♧</span><h3>还没有剧情委托</h3><p>在上方写明目标并点“推荐委托”，白会调用所选 API，根据当前世界、重要印象与连锁反应整理最多三项建议。信息不足时先到设置补充世界资料。</p></div>
              <div class="quest-grid"><article class="record quest-card" v-for="q in quests" :key="q.id" :data-quest-id="q.id"><div class="record-top"><span class="tag">{{({offered:'待接取',active:'进行中',completed:'已完成',dismissed:'已搁置'})[q.status]}}</span><small>{{q.world}}</small></div><h2>{{q.title}}</h2><p><b>完成目标：</b>{{q.objective}}</p><p class="subtle">缘由：{{q.reason}}</p><p v-if="q.sourceRippleId" class="subtle">关联连锁反应：{{rippleDescription(q.sourceRippleId)}}</p><p v-if="q.completionEventId" class="subtle">已核实结果：{{outcomeDescription(q.completionEventId)}} · 收益已统一计入事件与点数</p><div class="button-row"><button v-if="q.status==='active'" class="secondary" @click="c.close()">回聊天推进这个目标</button><button v-if="q.status==='offered'" class="primary" :disabled="s.busy" @click="c.taskAction(q.id,'active')">接取委托</button><button v-if="q.status==='active'" class="primary" :disabled="s.busy||!chatAvailable" @click="c.settle()">核对故事是否已完成目标</button><button v-if="q.status==='offered'||q.status==='active'" class="text-button" :disabled="s.busy" @click="c.taskAction(q.id,'dismissed')">暂且搁置</button></div></article></div>
            </template>

            <template v-else-if="s.tab==='memory'">
              <div class="section-title"><div><span class="eyebrow">FOUR PAGES / ONE ORIGIN</span><h1>记忆四表</h1><p>这里查看本轮给 AI 的记忆摘要；账本中的完整历史一直保留。</p></div><button class="secondary" @click="c.exportMemory()">导出数据库四表 ↓</button></div>
              <section class="memory-budget" aria-label="记忆预算"><div><b>{{s.memoryTokens}} / {{s.settings.memoryTokenBudget}}</b><small>{{s.memoryMethod||'等待计数'}} · 仅本插件记忆</small></div><label>每轮记忆预算<select v-model.number="s.settings.memoryTokenBudget" @change="c.saveSettings()"><option :value="2048">2048 Token · 精简</option><option :value="4096">4096 Token · 详细</option><option :value="8192">8192 Token · 扩展</option></select></label><p>完整历史留在本地；每轮按重要性与剧情相关性取摘要。{{s.memory?.omitted??0}} 条本轮未展开，仍保留原有事实与权益。</p></section>
              <form class="wish" @submit.prevent="c.refreshMemory()"><label class="sr-only" for="memory-query">记忆召回关键词</label><input id="memory-query" v-model="s.memoryQuery" maxlength="500" placeholder="人物、能力、旧世界、事件关键词…"/><button type="submit">召回相关记忆</button></form>
              <section v-for="table in s.memory?.tables??[]" :key="table.key" class="memory-table record" :data-memory-table="table.key"><div class="record-top"><h2>{{table.title}}</h2><span class="tag">本轮给 AI 的摘要</span></div><div class="table-scroll"><table role="table" :aria-label="table.title"><thead role="rowgroup"><tr role="row"><th v-for="heading in table.columns" :key="heading" scope="col" role="columnheader">{{heading}}</th></tr></thead><tbody role="rowgroup"><tr v-for="(row,i) in table.rows" :key="i" role="row"><td v-for="(cell,j) in row" :key="j" role="cell" :data-label="table.columns[j]">{{cell}}</td></tr></tbody></table></div><p v-if="!table.rows.length" class="subtle">尚无相关记录。</p></section>
              <details class="explanation"><summary>保存一条不可忽略的重要印象</summary><p>用于人物关系、承诺、重大选择和事实纠正。手动记忆不会自动加点；同一对象的新记录优先，旧记录仍可查。</p><form class="impression-form" @submit.prevent="c.saveImpression()"><label>人物 / 势力 / 事项<input v-model="s.impressionSubject" required maxlength="160"/></label><label>已经确认的印象<textarea v-model="s.impressionSummary" required maxlength="1200" rows="3"></textarea></label><label class="check"><input type="checkbox" v-model="s.impressionPinned"/>优先保留</label><button class="primary" type="submit">保存重要印象</button></form></details>
              <details class="explanation"><summary>印象历史档案（{{s.ledger.impressions?.length??0}}）</summary><article class="evidence" v-for="i in impressionArchive" :key="i.id"><b>{{i.subject}} · {{i.world}}</b><p>{{i.summary}}</p><small>{{i.source==='user'?'手动确认':'故事证据'}} · {{i.evidence}}</small></article></details>
              <details class="explanation"><summary>连锁反应历史（{{s.ledger.rippleHistory?.length??0}}）</summary><article class="evidence" v-for="(r,i) in [...(s.ledger.rippleHistory??[])].reverse().filter(r=>!s.memoryQuery||[r.world,r.source,r.tracking].join(' ').includes(s.memoryQuery))" :key="i"><b>{{r.source}} · {{r.world}}</b><p>当时已结算：{{r.settled}}</p><p>当时追踪：{{r.tracking}}</p><small>{{r.updatedAt}} · {{r.status==='active'?'当时追踪中':'当时已结束'}}（历史版本，不冒充当前状态）</small></article></details>
              <details class="explanation"><summary>查看实际注入文本</summary><pre class="receipt">{{s.memory?.text}}</pre></details>
              <p class="subtle">预算控制本插件注入及评估摘录，酒馆角色卡、聊天和其他世界书仍使用你自己的上下文设置。原生四表默认关闭世界书注入、自动填表频率为 0。请勿手动选择这些快照表填表，避免重复发送。</p>
            </template>

            <template v-else-if="s.tab==='database'">
              <span class="eyebrow">BUTTERFLY DATABASE</span><h1>把当前四表导入原数据库</h1><p class="lead">商店内的四表自动随账本更新；原数据库里导入的是快照，需要重新导入才能刷新。</p>
              <ol class="import-steps"><li>点下方“导出数据库四表”，保存当前摘要 JSON。</li><li>打开原数据库的“表格模板”，选择“导入模板 JSON”。</li><li>选择导出的文件，按原生提示保存并应用到目标聊天。</li></ol><p class="note">目标聊天已有其他表格时，先备份模板和表数据，再按数据库的合并流程保留原表。导入快照不保证自动合并，也不会修改商店余额。</p>
              <div class="database-card"><div class="db-icon">▤</div><h2>蝴蝶效应 · 四表记忆</h2><p>商店内的四表随任务和交易更新。导出的原生表格是当前记忆快照，默认只展示，AI 每轮只接收一份受预算控制的摘要。</p><button class="primary" @click="s.tab='memory'">查看四表与 Token 预算</button><button class="secondary" @click="c.exportMemory()">导出数据库四表</button><p class="subtle">官方原版数据库可以正常更新。白主题独立加载，原生四表通过导入快照刷新，不会绕过数据库的保存机制。</p></div>
              <div class="two-col"><article class="record"><span class="eyebrow">INDEPENDENT THEME</span><h2>白 · 空白棋局</h2><div class="swatches"><i style="background:#f5f5ff"></i><i style="background:#d7f3f7"></i><i style="background:#be9dec"></i><i style="background:#7250ad"></i></div><label class="check"><input type="checkbox" :disabled="!a.state.available" :checked="a.state.enabled" @change="a.setEnabled(($event.target as HTMLInputElement).checked)"/>启用完整白主题与 Q 版白</label><p>{{a.state.error||a.state.status}}</p><p>白／Q版白主题使用独立的酒馆助手脚本。在全局脚本库导入并启用后，此处可控制主题；停用脚本会恢复原数据库外观。更新脚本时替换旧版，避免同时启用两份。</p><a class="text-button" :href="assetBase+'/database/shiro-v2-theme.json'" download>仅下载原生配色文件 ↓</a></article><article class="record"><span class="eyebrow">PERSISTENT ARCHIVE</span><h2>历史保留，发送有度</h2><p>完整计功、固定报价、消费、所得、印象和委托都在本地账本。旧六表归档继续兼容，四表用于阅读与 AI 记忆。</p><button class="secondary" @click="c.exportLedger()">备份完整档案 ↓</button></article></div>
              <details class="explanation"><summary>旧六表兼容同步</summary><p>{{databaseSupport==='safe'?'检测到已核验的聊天绑定安全接口，可继续同步旧六表。':databaseSupport==='missing'?'尚未检测到数据库；如需完整白主题，请导入并启用独立主题脚本。':'当前为官方原版或未核验接口；自动原生写回暂停，商店与四表记忆照常更新。'}}</p><p>旧版自动六表同步需要固定兼容桥。更新为官方原版后不会继续调用它；不会退回可能写错聊天的接口。以前导入的旧六表，请在原生参数中将每张表更新频率设为 0，并关闭世界书导出，避免额外消耗 Token。</p><button class="secondary" :disabled="s.busy||databaseSupport!=='safe'" @click="c.enableTables()">接入当前聊天</button><button class="secondary" :disabled="databaseSupport!=='safe'" @click="c.sync()">重新同步旧六表</button><button class="secondary" @click="c.exportTables()">导出完整六表归档</button><p class="sync-status" role="status">{{s.syncStatus}}</p></details>
            </template>

            <template v-else-if="s.tab==='settings'"><span class="eyebrow">ORIGIN & CONNECTION</span><h1>设置与备份</h1><section class="record settings"><h2>当前本源</h2><label>选择跨世界接续的本源<select :value="s.settings.accountId" @change="changeAccount"><option v-for="a in s.accounts" :value="a.accountId">{{a.label}} · {{a.balance}} 点</option></select></label><p>当前酒馆登录账户：{{s.handle}}。角色、世界或 Persona 切换不会分割此本源。</p><div class="inline-form"><input v-model="s.accountLabel" aria-label="新本源名称" placeholder="新本源名称"/><button class="secondary" @click="c.createAccount()">建立独立本源</button></div></section><section class="record settings"><h2>API 与世界匹配</h2><label>生成连接<select v-model="s.settings.provider" @change="c.saveSettings()"><option value="host">酒馆当前 API（包含当前聊天与激活世界书）</option><option value="database">数据库 API 预设（角色资料、最近12条、绑定世界书）</option></select></label><label v-if="s.settings.provider==='database'">数据库预设名称<input v-model="s.settings.preset" @change="c.saveSettings()" placeholder="留空使用数据库默认预设"/></label><p>使用你已配置的连接。商店不单独存储或导出 API 密钥。</p><label>补充世界资料（地理、力量、技术、世界书遗漏的设定）<textarea v-model="s.settings.worldNotes" @change="c.saveSettings()" rows="4" maxlength="20000" placeholder="信息不足时可以在此补充；不能用来直接增加点数。"></textarea></label><label class="check"><input type="checkbox" v-model="s.settings.autoWorld" @change="c.saveSettings()"/>进入聊天时自动识别世界并匹配商品</label><label class="check"><input type="checkbox" v-model="s.settings.autoSettle" @change="c.saveSettings()"/>故事回复完成后自动核对新增因果</label><p class="subtle">自动功能会调用所选 API；也可关闭后在商店和账本中手动触发。</p></section><section class="record"><h2>账本备份</h2><p>账本保存在当前浏览器、当前酒馆地址下。换浏览器、清理站点数据或换服务器前，请导出完整备份。恢复为新本源，避免覆盖有效历史。</p><div class="button-row"><button class="primary" @click="c.exportLedger()">导出完整账本</button><button class="secondary" @click="c.exportLedger(true)">备份到酒馆服务器</button><button class="secondary" @click="input?.click()">恢复备份</button></div></section><details class="explanation"><summary>固定规则与实现边界</summary><p>1 点永远对应一份固化的健康、完整、未超凡成年人肉体与灵魂底蕴。本源基准不随世界、实力或余额改变。</p><p>首次独立有效改变至少 1 点。收益只来自实际成立的事实；重复结果不重复计功，加深仅计新增部分，未来收益不预支。</p><p>新计功标准与新商品价格由所选模型依据原文评估，并永久保存；原文未提供精确数值公式。语义判断应结合账本证据核对。数值实现支持最多 48 位整数和 18 位小数。</p><p>此版本固定验证于 SillyTavern 1.18.0 和龙血玄黄·数据库 1.2.5。其他版本需重新核验。</p></details></template>
          </template>
          <div v-else-if="s.ready" class="empty"><p>正在读取本源记录…</p><button class="secondary" @click="c.refresh()">重新读取</button></div>
          <footer class="page-footer"><span>♛ 白 · 蝶翼商店</span><span>同一标尺 · 同一份你</span></footer>
        </main>
      </div>
      <input ref="input" type="file" accept="application/json,.json" hidden @change="importFile"/>
      <div v-if="s.selectedQuote" class="modal-veil" @click.self="s.selectedQuote=null"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="quote-title"><button class="icon-button modal-close" aria-label="关闭规格" @click="s.selectedQuote=null">×</button><span class="eyebrow">IMMUTABLE EFFECT SPECIFICATION</span><h2 id="quote-title">{{s.selectedQuote.name}}</h2><p class="price-line">{{s.selectedQuote.price}} <small>因果点 / 份 · 永久定价</small></p><dl><template v-for="(label,field) in SPEC_LABELS"><dt>{{label}}</dt><dd>{{s.selectedQuote.spec[field]}}</dd></template></dl><p v-if="s.selectedQuote.differences?.length" class="note">相较 {{s.selectedQuote.previousQuoteId}} 的新增规格：{{s.selectedQuote.differences.map(k=>SPEC_LABELS[k]).join('、')}}</p><label class="quantity">兑换份数<input v-model.number="s.quantity" type="number" min="1" max="999999" step="1"/></label><p class="price-line">总计 {{totalPrice || '数量无效'}} <small v-if="totalPrice">因果点</small></p><p class="subtle">确认后按总计扣点，完整所得与回执立即保存。</p><div v-if="s.error" class="alert error" role="alert">{{s.error}}</div><button class="primary full" :disabled="s.busy||!totalPrice||!!totalShortfall" @click="c.buy()">{{!totalPrice?'请输入有效整数份数':totalShortfall?`还差 ${totalShortfall} 点`:'确认兑换 · 完整到账'}}</button></section></div>
      <div v-if="inventoryModal" class="modal-veil" @click.self="inventoryModal=null"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="inventory-title"><button class="icon-button modal-close" @click="inventoryModal=null" aria-label="关闭登记">×</button><h2 id="inventory-title">{{inventoryModal.action==='use'?'登记实际消耗':'记录实际移交'}}</h2><p>{{inventoryModal.name}}</p><label>已实际发生的数量<input type="number" min="1" :max="inventoryModal.max" step="1" v-model.number="inventoryQuantity"/></label><label v-if="inventoryModal.action==='transfer'">接收者<input v-model="recipient" placeholder="填写实际归属对象"/></label><p>仅在故事中已实际发生时登记。余额不变，所得数量与归属记录同步更新。</p><div v-if="s.error" class="alert error">{{s.error}}</div><button class="primary full" @click="commitInventory()">确认记录实际变化</button></section></div>
    </section>
  </div>
</template>
